---
version: '3.7'
services:
  sb:
    build: sb
    volumes:
     - type: volume
       source: papka
       target: /tmp/boxfuse-sample-java-war-hello/target
  pr:    
    build: pr  
    depends_on:
      - sb
    ports:
      - "8080:8080"   
    volumes:
      - type: volume
        source: papka
        target: /usr/local/tomcat/webapps
volumes:
  papka:      

