---
version: '3.7'
services:
  sb:
    build: sb
    volumes:
     - vol1:/tmp/boxfuse-sample-java-war-hello/target
  pr:    
    build: pr  
    depends_on:
     - sb
    ports:
     - "8080:8080"   
    volumes:
     - vol1:/usr/local/tomcat/webapps
volumes:
  vol1:      

