---
version: '3.7'
services:
  sb:
    build: sb
    volumes:
      - type: bind
        source: /home/ubuntu/boxfuse
        target: /tmp/boxfuse-sample-java-war-hello
  pr:    
    build: pr  
    depends_on:
      - sb
    volumes:
      - type: bind
        source: /home/ubuntu/boxfuse
        target: /tmp/boxfuse-sample-java-war-hello
